name: Build caddy Compress with UPX

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  schedule:
    - cron: 0 16 */7 * *

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Compress with UPX
        run: |
         # install upx
          wget https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-amd64_linux.tar.xz 
          tar -Jxf upx*.tar.xz
          sudo cp upx*/upx /usr/bin
          
          # set work dir
          mkdir -p musldist
          cd musldist
          
          # linux_amd64
          CADDY_LATEST=$(wget -qO- "https://api.github.com/repos/caddyserver/caddy/releases/latest" | awk -F [v\"] '/"tag_name"/{print $5}' || echo '2.7.6')
          wget -c https://github.com/caddyserver/caddy/releases/download/v${CADDY_LATEST}/caddy_${CADDY_LATEST}_linux_amd64.tar.gz -qO- | tar xz -C ./ caddy
          chmod +x caddy
          upx -1 caddy

      - name: Upload dist
        uses: actions/upload-artifact@main
        with:
          name: caddy
          path: |
              musldist

      - name: Generate release tag
        id: tag
        run: echo "::set-output name=release_tag::caddy"

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
              musldist/*

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_KEY }}
